webapp/tyresapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page

from .views import (
    TyresListView,
    TyreDetails,
    BasketView,
    OrderView,
    SortingView,
    FiltrationView,
    ExampleView,
)

app_name = "tyresapp"


urlpatterns = [
    path("", TyresListView.as_view(), name="tyres"),
    path("tyre_detail/<int:pk>/<int:tg_id>", TyreDetails.as_view(), name="tyre_details"),
    path("basket/<int:tg_id>/", BasketView.as_view(), name="basket"),
    path("order/<int:tg_id>", OrderView.as_view(), name="order"),
    path("sorting/", SortingView.as_view(), name="sorting"),
    path("filtration/", FiltrationView.as_view(), name="filtration"),
    path("example/", ExampleView.as_view(), name="example")
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tyres/", include("tyresapp.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

webapp/tyresapp/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User
# Create your models here.


def tyre_preview_directory_path(instance: "TyreImage", filename: str) -> str:
    return "tyres/tyre{pk}/preview/{filename}".format(
        pk=instance.tyre.pk,
        filename=filename
    )


class Tyre(models.Model):
    code = models.CharField(max_length=100, db_index=True)
    name = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    tyres_parameters = models.CharField(max_length=100)
    disks_parameters = models.CharField(max_length=100, null=True)
    tread_remain = models.CharField(max_length=100)
    stage = models.CharField(max_length=20)
    season = models.CharField(max_length=20)
    status = models.CharField(max_length=20, default=0)
    location = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Tyre(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse("tyresapp:tyre_details", kwargs={"pk": self.pk})


def tyre_images_directory_path(instance: "TyreImage", filename: str) -> str:
    return "tyres/tyre_{pk}/images/{filename}".format(
        pk=instance.tyre.pk,
        filename=filename
    )


class TyreImage(models.Model):
    tyre = models.ForeignKey(Tyre, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=tyre_preview_directory_path)


class Order(models.Model):
    tg_id = models.IntegerField(default=0)
    tyre_id = models.IntegerField(default=0)

webapp/tyresapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView

from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

from aiogram import Bot

from .config import token, group_id
from .models import Tyre, Order


class TyresListView(ListView):
    def get_queryset(self):
        return Tyre.objects.all()

    def get_orders(self):
        return Order.objects.all()

    def get(self, request):
        tyres = self.get_queryset()
        orders = self.get_orders()
        tyres_list = []
        tyres_pk_list = [order.tyre_id for order in orders]

        for tyre in tyres:
            if tyre.status not in ["booked", "sold"] and tyre.pk not in tyres_pk_list:
                tyres_list.append(tyre)

        context = {"tyres": tyres_list, "search_value": "", "filtration": "Все товары"}
        return render(request, "tyresapp/index.html", context=context)

    def post(self, request):
        search = request.POST.get("search")
        tyres = self.get_queryset()
        tyres_list = []

        for tyre in tyres:
            if search.lower() in tyre.name.lower() and tyre.status == "stock":
                tyres_list.append(tyre)

        context = {"tyres": tyres_list, "search_value": search}
        return render(request, "tyresapp/index.html", context=context)


class TyreDetails(DetailView):
    def get_queryset(self, pk):
        return Tyre.objects.filter(pk=pk)

    def get(self, request, pk, tg_id):
        tyre = self.get_queryset(pk=pk)
        context = {"tyre": tyre[0]}

        return render(request, "tyresapp/product_card.html", context=context)

    def post(self, request, pk, tg_id):
        tg_id = int(request.POST.get("tg_id"))
        Order.objects.create(
            tg_id=tg_id,
            tyre_id=pk
        )

        booked_tyre = Tyre.objects.filter(pk=pk)[0]
        booked_tyre.status = "booked"
        booked_tyre.save()

        tyre = self.get_queryset(pk=pk)
        context = {"tyre": tyre[0]}

        return render(request, "tyresapp/product_card_added.html", context=context)


class BasketView(ListView):
    context_object_name = "orders"

    def get_queryset(self, tg_id):
        return Order.objects.filter(tg_id=tg_id)

    def get(self, request, tg_id):
        orders = self.get_queryset(tg_id)
        tyres = []
        end_price = 0
        for elem in orders:
            end_price += Tyre.objects.filter(pk=elem.tyre_id)[0].price
            tyres.append(Tyre.objects.filter(pk=elem.tyre_id)[0])

        context = {"tyres": tyres, "tg_id": tg_id, "end_price": end_price}
        return render(request, "tyresapp/basket.html", context=context, status=404)

    def post(self, request, tg_id):
        isClear = request.POST.get("isClear")
        if isClear == "1":
            orders = self.get_queryset(tg_id=tg_id)
            for order in orders:
                elem = Order.objects.get(pk=order.pk)
                elem.delete()

            context = {"tyres": [], "tg_id": tg_id, "end_price": 0}

        else:
            tyre_id = request.POST.get("deleteOne")
            orders = self.get_queryset(tg_id=tg_id)
            for order in orders:
                if order.tyre_id == int(tyre_id):
                    elem = Order.objects.get(pk=order.pk)
                    elem.delete()
                    tire = Tyre.objects.filter(pk=tyre_id)[0]
                    tire.status = "stock"
                    tire.save()

            tyres = []
            end_price = 0
            for elem in orders:
                end_price += Tyre.objects.filter(pk=elem.tyre_id)[0].price
                tyres.append(Tyre.objects.filter(pk=elem.tyre_id)[0])

            context = {"tyres": tyres, "tg_id": tg_id, "end_price": end_price}

        return render(request, "tyresapp/basket.html", context=context, status=404)


class OrderView(TemplateView):
    async def get_queryset(self, tg_id):
        return Order.objects.filter(tg_id=tg_id)

    async def get(self, request, tg_id):
        orders = await self.get_queryset(tg_id=tg_id)
        warehouses = []
        full_price = 0
        codes = []
        for elem in orders:
            codes.append(Tyre.objects.filter(pk=elem.tyre_id)[0].code)
            warehouse = Tyre.objects.filter(pk=elem.tyre_id)[0].location
            if warehouse not in warehouses:
                warehouses.append(warehouse)
            full_price += Tyre.objects.filter(pk=elem.tyre_id)[0].price

        context = {"warehouses": warehouses, "full_price": full_price, "tg_id": tg_id}
        return render(request, "tyresapp/order.html", context=context)

    async def post(self, request, tg_id):
        if request.method == "POST":
            orders = await self.get_queryset(tg_id=tg_id)

            FIO = request.POST.get("fio")
            phone = request.POST.get("phone")
            email = request.POST.get("email")
            comment = request.POST.get("comment")

            text = "Новый заказ!\n" \
                   "Коды:"

            for num, elem in enumerate(orders):
                tyre_info = Tyre.objects.filter(pk=elem.tyre_id)[0]
                text += f"{num + 1}) Код: {tyre_info.code}\n" \
                        f"Наименование: {tyre_info.name}\n" \
                        f"Размерность: {tyre_info.tyres_parameters}\n" \
                        f"Цена: {tyre_info.price}\n"

            user_data = f"\nФИО: {FIO}\n" \
                        f"Телефон: {phone}\n" \
                        f"Email: {email}\n\n" \
                        f"Комментарий к заказу: {comment}"

            bot = Bot(token=token)
            await bot.send_message(
                chat_id=group_id,
                text=text + user_data
            )

            orders = Order.objects.filter(tg_id=tg_id)
            for order in orders:
                tyre = Tyre.objects.filter(pk=order.tyre_id)[0]
                tyre.status = "sold"
                tyre.save()

                order_object = Order.objects.get(pk=order.pk)
                order_object.delete()

            return render(request, "tyresapp/end_order.html")


class SortingView(TemplateView):
    def get_tires(self):
        return Tyre.objects.all()

    def get_orders(self):
        return Order.objects.all()

    def get(self, request):
        return render(request, "tyresapp/sorting.html")

    def post(self, request):
        method = request.POST.get("ff")
        # Sorting.objects.create(
        #     tg_id=tg_id,
        #     method=method
        # )

        tyres = self.get_tires()
        orders = self.get_orders()
        tyres_list = []
        tyres_pk_list = [order.tyre_id for order in orders]

        for tyre in tyres:
            if tyre.status not in ["booked", "sold"] and tyre.pk not in tyres_pk_list:
                tyres_list.append(tyre)

        if method == "new":
            tyres_list = sorted(tyres_list, key=lambda lst: lst.created_at)

        elif method == "ascending":
            tyres_list = sorted(tyres_list, key=lambda tire: tire.price)

        elif method == "descending":
            tyres_list = sorted(tyres_list, key=lambda tire: tire.price, reverse=True)

        context = {"tyres": tyres_list, "search_value": "", "filtration": "Все товары"}
        return render(request, "tyresapp/index.html", context=context)


class FiltrationView(TemplateView):
    def get_locations(self):
        return {
            1: "Москва",
            2: "Ростов",
            3: "Воро""неж",
            4: "Краснодар",
            5: "Минеральные Воды",
            6: "Тюмень",
            7: "Волгоград",
            8: "Ставрополь",
            9: "Сургут"
        }

    def get_category_name(self):
        return {
            "product_category": "Категория товара.",
            "manufacturer": "Производитель.",
            "weight": "Ширина Шин.",
            "height": "Высота Шин.",
            "seasonality": "Сезонность.",
            "diameter": "Диаметр (размер).",
            "thorns": "Шипы.",
            "location": "Локация."
        }

    def get_tires(self):
        return Tyre.objects.all()

    def get(self, request):
        return render(request, "tyresapp/filtration.html")

    def post(self, request):
        min = request.POST.get("min")
        min = int(min) if min else 0
        max = request.POST.get("max")
        max = int(max) if max else 1000000
        product_category = request.POST.get("product_category")
        if "wheels" == product_category:
            product_category = "колес"
        else:
            product_category = "резина"

        manufacturer = request.POST.get("manufacturer")
        weight = request.POST.get("weight")
        height = request.POST.get("height")
        seasonality = request.POST.get("seasonality")
        if seasonality == "Всесезонные":
            seasonality = ""
        diameter = request.POST.get("diameter")
        # thorns = request.POST.get("thorns")
        # thorns = int(thorns) if thorns else 0
        location = request.POST.get("location")
        if location:
            locations_dict = self.get_locations()
            location = locations_dict[int(location)]

        tires = self.get_tires()
        tires_list = []
        for tire in tires:
            if min <= tire.price <= max and product_category in tire.name.lower() and manufacturer in tire.model and str(weight) in str(tire.tyres_parameters) and str(height) in str(tire.tyres_parameters) and diameter in str(tire.tyres_parameters) and seasonality in tire.season and location in tire.location:
                tires_list.append(tire)

        fields_list = ["product_category", "manufacturer", "weight", "height", "seasonality", "diameter", "location"]
        russian_fields_dict = self.get_category_name()
        filtration_string = ""
        for field in fields_list:

webapp/tyresapp/templates/tyresapp/basket.html
{% load static %}
<html lang="en">
          <head>
            <meta charset="utf-8">
          
            <title>Basket</title>
            <link rel="icon" type="image/svg+xml" href="/vite.svg" />
            <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->
            <meta name="format-detection" content="telephone=no" />
            <meta name="MobileOptimized" content="176" />
            <meta name="HandheldFriendly" content="True" />
            <meta name="robots" content="noindex,nofollow" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />

            <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet">

            <link rel="stylesheet" href="{% static 'css/basket_styles.css' %}">
            <script src="https://telegram.org/js/telegram-web-app.js"></script>

          </head>
          
          <body>
            {% block body %}
              <form id="clear_bin" method="post" class=frame>
                <input type="hidden" id="clearInput" name="isClear" value="0">
                <input type="hidden" id="deleteTyre" name="deleteOne" value="0">

                {% csrf_token %}
                {% url 'tyresapp:tyres' as tyres_url %}
                <a href="{{ tyres_url }}">
                  <span  class="back_text">Назад</span>
                  <img class="back_image" src="{% static 'photos/image_1.png' %}">
                </a>
                
                <div class="title" >
                  <span  class="e18_1286">Корзина</span>
                  <span  class="e18_1328" id="clear" onclick="clearBin()">Очистить</span>
                </div>
                
                {% if tyres %}
                  {% for tyre in tyres %}
                    <div class="bin_card">
                      {% for image in tyre.images.all %}
                        <img  class="product_image" src="{{ image.image.url }}">
                      {% endfor %}
                    
                      <img class="cross" src="{% static 'photos/cross.png' %}" id="{{ tyre.pk }}">

                      <div class="model">
                        {{ tyre.model }}<br>
                        Шины {{ tyre.tyres_parameters }}
                        {% if tyre.disks_parameters %}
                          <br>Диски {{ tyre.disks_parameters }}
                        {% endif %}
                      </div>
                      
                      <div  class="location">Шины {{ tyre.tyres_parameters }}<br>Локация: {{ tyre.location }}</div>
                      <span  class="price">
                        {{ tyre.price }}₽
                      </span>
                      <!-- <div  class="minus_button">
                        <span  class="minus">-</span>
                      </div>
                      <span  class="number">1</span>
                      <div  class="plus_button">
                        <span  class="plus">+</span>
                      </div> -->
                    </div>
                  {% endfor %}
                {% endif %}

                {% if 6 >= tyres|length %}
                  <script>
                    let frameObject = document.getElementById("clear_bin")
                    frameObject.style.height = "100%";
                  </script>
                {% endif %}

                <div style="display: block; width: 100%; height: 80px; background-color:rgba(255, 255, 255, 1);"></div>
                
                <div style="background-color:rgba(255, 255, 255, 1); position: fixed; bottom: 50px; display: flex; width: 300px; height: 30px;">
                  <span  class="end">Итого:</span>
                  <span  class="end_price">{{ end_price }} ₽</span>
                </div>
                
                {% if tyres %}
                  <a id="basketUrlID" href="#">
                    <div class="bin">
                      <div class="bin_background">
                        <div class="blue_bin">
                          <span class="bin_text">Оформить заказ</span>
                        </div>
                      </div>
                    </div>
                  </a>

                  <script>
                    let tg = window.Telegram.WebApp;
                    let tg_id = tg.initDataUnsafe.user.id;
                    var url = "{% url 'tyresapp:order' tg_id=0 %}".replace(0, tg_id);
                    document.getElementById("basketUrlID").href = url;
                  </script>
                {% else %}
                  <a href="{% url 'tyresapp:tyres' %}">
                    <div class="bin">
                      <div class="bin_background">
                        <div class="blue_bin">
                          <span class="bin_text">Каталог</span>
                        </div>
                      </div>
                    </div>
                  </a>
                {% endif %}
              </div>
            </form>
            
            <script>
              var buttonItems = document.querySelectorAll('.cross'),
                  index, button;

              for (index = 0; index < buttonItems.length; index++) {
                  button = buttonItems[index];
                  button.addEventListener('click', function (elem) {
                      let form = document.getElementById("clear_bin")
                      document.getElementById("deleteTyre").value = button.id;
                      form.submit()
                  });
              }
            </script>

            <script>
              document.getElementById("clear").onclick = clearBin;
              function clearBin() {
                let form = document.getElementById("clear_bin")
                let inputBin = document.getElementById("clearInput")
                inputBin.value = 1;
                form.submit()
              }
            </script>
          {% endblock %}  
  </body>
</html>

webapp/tyresapp/templates/tyresapp/index.html
{% load static %}
<html lang="en">
 
<head>
  <meta charset="utf-8">

  <title>Fresh Shop</title>
  <meta name="description" content="Figma htmlGenerator">
  <meta name="author" content="htmlGenerator">
  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
  <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="https://telegram.org/js/telegram-web-app.js"></script>
</head>

<body>
  {% block body %}
    <div class=frame id="frameID">
      <div style="display: flex;">
        <form id="searchID" method="post" style="margin-bottom: 5px;">
          {% csrf_token %}
          <input type="search" placeholder="Я ищу..." name="search" value="{{ search_value }}">
        </form>
      
        <a id="sortID" href="{% url 'tyresapp:sorting' %}">
          <div class="filters_block">
            <img class="filters_photo" src="{% static 'photos/filters.png' %}" alt="">
          </div>
        </a>
      </div>
    
      <a id="filterID" href="{% url 'tyresapp:filtration' %}" style="text-decoration: none;">
        <div class="filters">
            <div class="card_text">
              <div class="filter_name">
                Фильтры
              </div>
              <div class="sorted_filters">{{ filtration }}</div>
            </div>

            <img class="open_filters" src="{% static 'photos/image_1.png' %}" alt="">
          </div>
      </a>

        {% if tyres %}
          {% for tyre in tyres %}
            <div class="product_card">
              {% for image in tyre.images.all %}
                <a href="{% url 'tyresapp:tyre_details' pk=tyre.pk tg_id=0 %}">
                  <img class="product_image" src="{{ image.image.url }}">
                </a>
              {% endfor %}
              <div class="card_text">
                <div class="price">
                  {{ tyre.price }} ₽
                </div>
                
                {% if tyre.model|length > 25 %}
                  <div class="little_model">
                    {{ tyre.model }}
                  </div>
                {% else %}
                  <div class="model">
                    {{ tyre.model }}
                  </div>
                {% endif %}

                <div class="classification">
                  {{ tyre.tyres_parameters }}
          
                </div>
              </div>
              <a href="{% url 'tyresapp:tyre_details' pk=tyre.pk tg_id=0 %}">
                <div class="button">
                  <div class="button_background"><span class="add_text">+ Добавить</span></div>
                </div>
              </a>
            </div>
          {% endfor %}
          {% if 6 >= tyres|length %}
            <script>
              let frameObject = document.getElementById("frameID")
              frameObject.style.height = "100%";
            </script>
          {% endif %}
        {% else %}
          <script>
            let frameObject = document.getElementById("frameID")
            frameObject.style.height = "100%";
          </script>
          <div class="end_text">
            По данному запросу ничего не найдено
          </div>
        {% endif %}
      


      <div style="display: block; width: 100%; height: 50px; background-color:rgba(255, 255, 255, 1);"></div>
      <a id="basketUrlID" href="{% url 'tyresapp:basket' tg_id=0 %}">
        <div class="bin">
          <div class="bin_background">
            <div class="blue_bin">
              <span class="bin_text">Корзина</span>
            </div>
          </div>
        </div>
      </a>
      </div>
    </div>
  {% endblock %}
  <script>
    let tg = window.Telegram.WebApp;
    var tg_id = tg.initDataUnsafe.user.id;

    tg.expand();
    var url = "{% url 'tyresapp:basket' tg_id=0 %}".replace(0, tg_id);
    document.getElementById("basketUrlID").href = url;

    document.addEventListener('touchstart', function(event) {
      var focusedElement = document.activeElement;
      if (focusedElement.tagName === 'INPUT' || focusedElement.tagName === 'TEXTAREA') {
          focusedElement.blur();
          var inputMethod = document.createElement('input');
          inputMethod.setAttribute('type', 'text');
          document.body.appendChild(inputMethod);
          inputMethod.focus();
          inputMethod.parentNode.removeChild(inputMethod);
      }
    });

  </script>
  
</body>

</html>

webapp/tyresapp/templates/tyresapp/index2.html
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">

  <title>Fresh Shop</title>
  <meta name="description" content="Figma htmlGenerator">
  <meta name="author" content="htmlGenerator">
  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
  <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <script src="https://telegram.org/js/telegram-web-app.js"></script>
</head>

<body>
  {% block body %}
    <div class=frame id="frameID">
      <div style="display: flex;">
        <form id="searchID" method="post" style="margin-bottom: 5px;">
          {% csrf_token %}
          <input type="search" placeholder="Я ищу..." name="search" value="{{ search_value }}">
        </form>
      
        <a href="{% url 'tyresapp:sorting' %}">
          <div class="filters_block">
            <img class="filters_photo" src="{% static 'photos/filters.png' %}" alt="">
          </div>
        </a>
      </div>
    
      <a href="{% url 'tyresapp:filtration' %}" style="text-decoration: none;">
        <div class="filters">
            <div class="card_text">
              <div class="filter_name">
                Фильтры
              </div>
              <div class="sorted_filters">Все товары</div>
            </div>

            <img class="open_filters" src="{% static 'photos/image_1.png' %}" alt="">
          </div>
      </a>

        {% if tyres %}
          {% for tyre in tyres %}
            <div class="product_card">
              {% for image in tyre.images.all %}
                <img class="product_image" src="{{ image.image.url }}">
              {% endfor %}
              <div class="card_text">
                <div class="price">
                  {{ tyre.price }} ₽
                </div>
                
                {% if tyre.model|length > 25 %}
                  <div class="little_model">
                    {{ tyre.model }}
                  </div>
                {% else %}
                  <div class="model">
                    {{ tyre.model }}
                  </div>
                {% endif %}

                <div class="classification">
                  {{ tyre.tyres_parameters }}
          
                </div>
              </div>
              <a href="{% url 'tyresapp:tyre_details' pk=tyre.pk tg_id=0 %}">
                <div class="button">
                  <div class="button_background"><span class="add_text">+ Добавить</span></div>
                </div>
              </a>
            </div>
          {% endfor %}
          {% if 6 >= tyres|length %}
            <script>
              let frameObject = document.getElementById("frameID")
              frameObject.style.height = "100%";
            </script>
          {% endif %}
        {% else %}
          <script>
            let frameObject = document.getElementById("frameID")
            frameObject.style.height = "100%";
          </script>
          <div class="end_text">
            По данному запросу ничего не найдено
          </div>
        {% endif %}
      


      <div style="display: block; width: 100%; height: 50px; background-color:rgba(255, 255, 255, 1);"></div>
      <a id="basketUrlID" href="{% url 'tyresapp:basket' tg_id=0 %}">
        <div class="bin">
          <div class="bin_background">
            <div class="blue_bin">
              <span class="bin_text">Корзина</span>
            </div>
          </div>
        </div>
      </a>
      </div>
    </div>
  {% endblock %}
  <script>
    let tg = window.Telegram.WebApp;
    var tg_id = tg.initDataUnsafe.user.id;

    tg.expand();
    var url = "{% url 'tyresapp:basket' tg_id=0 %}".replace(0, tg_id);
    document.getElementById("basketUrlID").href = url;

    document.addEventListener('touchstart', function(event) {
      var focusedElement = document.activeElement;
      if (focusedElement.tagName === 'INPUT' || focusedElement.tagName === 'TEXTAREA') {
          focusedElement.blur();
          var inputMethod = document.createElement('input');
          inputMethod.setAttribute('type', 'text');
          document.body.appendChild(inputMethod);
          inputMethod.focus();
          inputMethod.parentNode.removeChild(inputMethod);
      }
    });

  </script>
  
</body>

</html>

webapp/tyresapp/templates/tyresapp/product_card.html
{% load static %}
<html lang="en"> 
          <head>
            <meta charset="utf-8">
          
            <title>Tyre detail</title>
            <meta name="description" content="Figma htmlGenerator">
            <meta name="author" content="htmlGenerator">


            <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet">

            <link rel="stylesheet" href="{% static 'css/product_card_styles3.css' %}">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <script src="https://telegram.org/js/telegram-web-app.js"></script>

          </head>
          
          <body>
            <div class="frame">
              {% url 'tyresapp:tyres' as tyres_url %}
              <a href="{{ tyres_url }}">
                <span  class="back_text">Назад</span>
                <img class="back_image" src="{% static 'photos/image_1.png' %}">
              </a>
              
              {% for image in tyre.images.all %}
                <img  class="e29_15" src="{{ image.image.url }}">
              {% endfor %}
              
              <span  class="company_title">Шинный магазин FRESH</span>
              <span  class="bot_title">бот</span>
                
              <div class=e29_6>
                <div  class="e29_8">
  
                </div></div>
                <span  class="e29_9">
                  {{ tyre.model }}<br>
                  Шины {{ tyre.tyres_parameters }}
                  {% if tyre.disks_parameters %}
                    <br>Диски {{ tyre.disks_parameters }}
                  {% endif %}
                </span>
                <span  class="price">{{ tyre.price }} ₽</span>
                <span  class="e29_11">Комплект, 4 шт.</span>
                <span  class="e29_12"> 
                  Остаток протектора: <b>{{ tyre.tread_remain }}</b><br>
                  Состояние: <b>{{ tyre.stage }}</b><br>
                  Сезон: <b>{{ tyre.season }}</b><br>
                  Локация: <b>{{ tyre.location }}</b>
                </span>
                
                <form id="blueButton" method="post">
                  {% csrf_token %}
                  <div class="blue_button" style="cursor: pointer;" onclick="endOrder()">
                    <span class="add_text">+ Добавить</span>
                  </div>
                  <input id="tgID" type="hidden" name="tg_id">
                </form>
                
                <a id="basketUrlID" href="#">
                  <div class="bin">
                    <div class="bin_background">
                      <div class="blue_bin">
                        <span class="bin_text">Корзина</span>
                      </div>
                    </div>
                  </div>
                </a>
            </div>
           <script>
              let tg = window.Telegram.WebApp;
              tg.expand();
              var tg_id = tg.initDataUnsafe.user.id;
              
              document.getElementById('blueButton').onclick = endOrder;
              function endOrder() {
                  let form = document.getElementById("blueButton")
                  document.getElementById("tgID").value = tg_id;
                  form.submit()
              }

              var url = "{% url 'tyresapp:basket' tg_id=0 %}".replace(0, tg_id);
              document.getElementById("basketUrlID").href = url;
            </script>
          </body>
          </html>